services:
  - type: web
    name: discord-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: BANK_NAME
        sync: false
      - key: BANK_NUMBER
        sync: false
      - key: SEPAY_TOKEN
        sync: false
      - key: API_BASE
        sync: false
      - key: WEBHOOK_PORT
        value: 8080